version: "3.9"
services:
  ds-playground:
    build: .
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - .:/workspaces/ds-playground

    # Keep container running until explicitly stopped
    command: /bin/sh -c "while true; do sleep 1; done"
