version: "3.9"
services:
  playground:
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
    volumes:
      - .:/workspaces/r
    command: /bin/sh -c "while true; do sleep 1; done"
